require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - 'bin/**'
    - 'db/schema.rb'
    - 'vendor/**/*'
  TargetRubyVersion: 2.6
  TargetRailsVersion: 6.0



# -----------------------------------------------------------------------------
#                                   RAILS

Rails:
  Enabled: true



# -----------------------------------------------------------------------------
#                                   RSPEC

RSpec:
  Include:
    - 'spec/**/*_spec.rb'
    - 'spec/spec_helper.rb'
    - 'spec/rails_helper.rb'

RSpec/ContextWording:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/ExpectInHook:
  Enabled: false

RSpec/FilePath:
  Exclude:
    - 'spec/client/**/*_spec.rb'

RSpec/MessageSpies:
  Enabled: false

RSpec/MissingExampleGroupArgument:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Max: 5




# -----------------------------------------------------------------------------
#                                   Layout

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/CaseIndentation:
  EnforcedStyle: end
  SupportedStyles:
    - case
    - end
  IndentOneStep: true

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/LineLength:
  Exclude:
    - 'db/**/*'
    - 'spec/**/*'
    - 'config/**/*'

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/SpaceInsideBlockBraces:
  EnforcedStyle: space
  EnforcedStyleForEmptyBraces: no_space
  SpaceBeforeBlockParameters: false

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space


# -----------------------------------------------------------------------------
#                                    Lint

#
# False positives:
#   * expect { something }.to change { something } often triggers this
#
Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*_spec.rb'



# -----------------------------------------------------------------------------
#                                   Metrics

Metrics/BlockLength:
  Exclude:
    - 'db/**/*'
    - 'spec/**/*'
    - 'config/**/*'
    - '**/*.rake'

Metrics/ClassLength:
  Max: 200

Metrics/MethodLength:
  Exclude:
    - 'db/**/*'



# -----------------------------------------------------------------------------
#                                   Style

Style/BracesAroundHashParameters:
  EnforcedStyle: context_dependent

#
# Both styles or mixtures are reasonable
#
Style/ClassAndModuleChildren:
  EnforcedStyle: compact
  Enabled: false

#
# Would be better but unlikely...
#
Style/Documentation:
  Enabled: false

Style/RaiseArgs:
  EnforcedStyle: compact

#
# Quick single line rescues in specs
#
Style/RescueModifier:
  Exclude:
    - 'spec/**/*_spec.rb'

#
# Quick single line rescues in specs
#
Style/RescueStandardError:
  Exclude:
    - 'spec/**/*_spec.rb'

#
# Often used pattern in chaining subjects in specs
#
Style/Semicolon:
  Exclude:
    - 'spec/**/*_spec.rb'

Style/SignalException:
  EnforcedStyle: only_raise
