---
services:
  postgres:
    image: postgres:18@sha256:52e6ffd11fddd081ae63880b635b2a61c14008c17fc98cdc7ce5472265516dd0
    restart: always
    environment:
      POSTGRES_USER: openmensa
      POSTGRES_PASSWORD: openmensa
      POSTGRES_DB: openmensa
    volumes:
      - postgres:/var/lib/postgresql/data

  openmensa:
    image: ghcr.io/openmensa/openmensa:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      DATABASE_URL: postgresql://openmensa:openmensa@postgres/openmensa
      FORCE_SSL: "no"
    ports:
      - 8080:80
    depends_on:
      - postgres

volumes:
  postgres:
  www:
