---
x-openmensa: &x-openmensa
  image: ghcr.io/openmensa/openmensa:latest
  build:
    context: .
    dockerfile: Dockerfile
  restart: unless-stopped
  read_only: true
  environment:
    DATABASE_URL: postgresql://openmensa:openmensa@postgres/openmensa
  tmpfs:
    - /tmp
  depends_on:
    postgres:
      condition: service_healthy
    init:
      condition: service_completed_successfully

services:
  init:
    <<: *x-openmensa
    command: rails db:create db:migrate
    restart: "no"
    depends_on:
      postgres:
        condition: service_healthy

  server:
    <<: *x-openmensa
    ports:
      - 3000:80

  jobs:
    <<: *x-openmensa
    command: jobs

  postgres:
    image: postgres:18@sha256:52e6ffd11fddd081ae63880b635b2a61c14008c17fc98cdc7ce5472265516dd0
    restart: unless-stopped
    environment:
      POSTGRES_USER: openmensa
      POSTGRES_PASSWORD: openmensa
      POSTGRES_DB: openmensa
    volumes:
      - postgres:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U openmensa -d openmensa"]
      interval: 1s
      timeout: 5s
      retries: 30

volumes:
  postgres:
