# Broader ecosystem checks for the repository, such as linting actions
# for workflows or security checks.
#
# Nothing directly related to the application codebase, language, code
# formatting or quality, or frameworks should be added here. Those
# should be added to `test.yml` instead.
---
name: Check

on:
  push:
  pull_request:

permissions: {}

jobs:
  actionlint:
    runs-on: ubuntu-26.04

    steps:
      - name: Harden runner
        uses: step-security/harden-runner@351661ca32ac09a36dc5ee2d536e3128f2a3c8ed # v2.22.0
        with:
          egress-policy: audit
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Check workflow files
        run: |
          echo "::add-matcher::.github/actionlint-matcher.json"
          bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
          ./actionlint

  zizmor:
    runs-on: ubuntu-26.04

    permissions:
      security-events: write

    steps:
      - name: Harden runner
        uses: step-security/harden-runner@351661ca32ac09a36dc5ee2d536e3128f2a3c8ed # v2.22.0
        with:
          egress-policy: audit
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Run zizmor 🌈
        uses: zizmorcore/zizmor-action@cc914d7f3750a2d13d75c7f184a1060aa0e9d482 # v0.6.4
        with:
          advanced-security: true
