---
name: Cleanup Pull Request Images

on:
  pull_request:
    types: [closed]

jobs:
  ghcr-cleanup-image:
    runs-on: ubuntu-latest

    permissions:
      packages: write

    steps:
      - name: Delete image
        uses: dataaxiom/ghcr-cleanup-action@374e2028c8fb93b7219f3771cd405fab95d3dec4 # v1
        with:
          delete-tags: pr-${{ github.event.pull_request.number }}
