---
name: maintenance-workflow-cleanup
on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:

jobs:
  delete-workflow-runs:
    runs-on: ubuntu-latest
    steps:
      - uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 180
          keep_minimum_runs: 50
