name: maintenance-registry

on:
  schedule:
    - cron: "48 6 * * *"
  workflow_dispatch:

jobs:
  ghcr-cleanup-image:
    runs-on: ubuntu-24.04

    permissions:
      packages: write

    steps:
      - name: Delete obsolete tags and images
        uses: jenskeiner/ghcr-container-repository-cleanup-action@v1
        with:
          exclude-tags: '^(?:main|latest|\d+(?:\.\d+){0,2}|pr-\d+)$'
          keep-n-tagged: 1
          keep-n-untagged: 0
          token: ${{ secrets.GITHUB_TOKEN }}
