name: maintenance-registry

on:
  schedule:
    - cron: "44 4 * * *"
  workflow_dispatch:

jobs:
  ghcr-cleanup-image:
    runs-on: ubuntu-24.04

    permissions:
      packages: write

    concurrency:
      group: ghcr-cleanup-image

    steps:
      - uses: dataaxiom/ghcr-cleanup-action@v1
