---
name: Cleanup GHCR Image Registry

on:
  schedule:
    - cron: "44 4 * * *"
  workflow_dispatch:

jobs:
  ghcr-cleanup-image:
    runs-on: ubuntu-24.04

    permissions:
      packages: write

    concurrency:
      group: ghcr-cleanup-image

    steps:
      - uses: dataaxiom/ghcr-cleanup-action@374e2028c8fb93b7219f3771cd405fab95d3dec4 # v1
        with:
          exclude-tags: main,latest
          older-than: 180 days
          delete-tags: "*"

      - uses: dataaxiom/ghcr-cleanup-action@374e2028c8fb93b7219f3771cd405fab95d3dec4 # v1
        with:
          delete-untagged: True
          delete-orphaned-images: True
