---
name: Cleanup Pull Request Images

on:
  pull_request:
    types: [closed]

jobs:
  ghcr-cleanup-image:
    runs-on: ubuntu-latest

    permissions:
      packages: write

    steps:
      - name: Delete image
        uses: dataaxiom/ghcr-cleanup-action@d52806a0dc70b430571a37da1fde39733ffd640f # v1
        with:
          delete-tags: pr-${{ github.event.pull_request.number }}
